#!/usr/bin/env python

import robot_upstart
import os

j = robot_upstart.Job(name="husky-core", interface=os.environ.get('ROBOT_NETWORK'), workspace_setup=os.environ.get('ROBOT_SETUP'))

# Stuff to launch on system startup.
j.add(package="husky_base", glob="launch/*")

if os.path.exists('/dev/clearpath/imu'):
  j.add(package="husky_bringup", glob="launch/um6_config/*")

if os.path.exists('/dev/microstrain'):
  j.add(package="husky_bringup", glob="launch/microstrain_config/*")

if os.path.exists('/dev/clearpath/gps'):
  j.add(package="husky_bringup", glob="launch/navsat_config/*")

if os.environ.get('HUSKY_UR5_IP'):
  j.add(package="husky_bringup", glob="launch/ur5_arm_config/*")

if os.environ.get('HUSKY_LMS1XX_IP'):
  j.add(package="husky_bringup", glob="launch/lms1xx_config/*")

if os.environ.get('HUSKY_DUAL_UR5_ENABLED'):
  j.add(package="husky_bringup", glob="launch/dual_ur5_arm_config/*")

if os.environ.get('FLIR_PTU_ENABLED'):
  j.add(package="husky_bringup", glob="launch/flir_ptu/*")

if os.environ.get('BUMBLEBEE_ENABLED'):
  j.add(package="husky_bringup", glob="launch/bumblebee/*")

if os.environ.get('ROBOTIQ_GRIPPERS_ENABLED'):
  j.add(package="husky_bringup", glob="launch/robotiq_s_model_grippers/*")

if os.environ.get('VELODYNE_VLP16_ENABLED'):
  j.add(package="husky_bringup", glob="launch/velodyne/*")

if os.environ.get("ROBOTIQ_FT_300_ENABLED'):
  j.add(package="husky_bringup", glob="launch/ft_300/*")

j.install()
