#!/bin/bash
source `rospack find rosbash`/rosbash

# Install the udev rules.
rospd husky_bringup/udev > /dev/null
echo "Installing udev rules."
sudo cp *.rules /etc/udev/rules.d/
popd > /dev/null
sudo udevadm trigger

# Install the upstart job, populate it with launch files.
install_pkg="rosrun robot_upstart install"
$install_pkg husky_base/launch --job husky-core
$install_pkg husky_description/launch --job husky-core --augment

# Install the teleop script if a joystick is attached.
if [ -e dev/input/js0 ]; then
  $install_pkg husky_teleop/launch --job husky-core --augment
fi

# Install the IMU launchers if the standard serial imu (um6) is attached.
if [ -e /dev/clearpath/imu ]; then
  $install_pkg husky_bringup/launch/imu_config --job husky-core --augment
fi

# Install the NavSat launchers if an NMEA GPS is attached.
if [ -e /dev/clearpath/gps ]; then
  $install_pkg husky_bringup/launch/navsat_config --job husky-core --augment
fi

# TODO: Automatically detect more standard peripherals.
