#!/bin/bash
source `rospack find rosbash`/rosbash

# Install the udev rules.
rospd husky_bringup/udev > /dev/null
echo "Installing udev rules."
sudo cp *.rules /etc/udev/rules.d/
popd > /dev/null
sudo udevadm trigger

# Install the upstart job, populate it with launch files.
#  * For the network interface, first try script parameter $1, then ROBOT_NETWORK, then eth0.
#  * For the setup.bash to use, first try ROBOT_SETUP, then fall back on setup.bash from active workspace.
#    In CPR-configured Ubuntu machines, /etc/ros/setup.bash is a wrapper on /opt/ros/xxx/setup.bash, and sets the
#    ROBOT_SETUP var to itself. This allows platform-wide env vars to be placed in that file.
install_pkg="rosrun robot_upstart install"
$install_pkg husky_base/launch --job husky-core \
                               --interface ${1-${ROBOT_NETWORK-eth0}} \
                               --setup ${ROBOT_SETUP-$(roscd; echo `pwd`/setup.bash)}
$install_pkg husky_description/launch --job husky-core --augment

# Install the teleop script if a joystick is attached.
if [ -e /dev/input/js0 ]; then
  $install_pkg husky_teleop/launch --job husky-core --augment
fi

# Install the IMU launchers if the standard serial imu (um6) is attached.
if [ -e /dev/clearpath/imu ]; then
  $install_pkg husky_bringup/launch/imu_config --job husky-core --augment
  EKF_SETTINGS_YAML=/etc/ros/$ROS_DISTRO/husky_ekf.yaml
  if [ -e "$EKF_SETTINGS_YAML" ]; then
    echo "EKF Settings yaml config already exists, skipping."
  else 
    echo "Installing EKF settings file to $EKF_SETTINGS_YAML"
    sudo cp "$(rospack find husky_bringup)/config/husky_ekf.yaml" "$EKF_SETTINGS_YAML"
  fi

fi

# Install the IMU launchers if Microstrain 3DMGX2 IMU is attached.
if [ -e /dev/microstrain ]; then
  $install_pkg husky_bringup/launch/microstrain_config --job husky-core --augment
  EKF_SETTINGS_YAML=/etc/ros/$ROS_DISTRO/husky_ekf.yaml
  if [ -e "$EKF_SETTINGS_YAML" ]; then
    echo "EKF Settings yaml config already exists, skipping."
  else 
    echo "Installing EKF settings file to $EKF_SETTINGS_YAML"
    sudo cp "$(rospack find husky_bringup)/config/husky_ekf.yaml" "$EKF_SETTINGS_YAML"
  fi

fi

# Install the NavSat launchers if an NMEA GPS is attached.
if [ -e /dev/clearpath/gps ]; then
  $install_pkg husky_bringup/launch/navsat_config --job husky-core --augment
  COMPASS_YAML=/etc/ros/$ROS_DISTRO/imu_compass.yaml
  if [ -e "$COMPASS_YAML" ]; then
    echo "Compass yaml config already exists, skipping."
  else 
    echo "Installing compass yaml file to $COMPASS_YAML"
    sudo cp "$(rospack find husky_bringup)/config/imu_compass.yaml" "$COMPASS_YAML"
  fi
fi

# TODO: Automatically detect more standard peripherals.
