#!/bin/bash
source `rospack find rosbash`/rosbash

# Install the udev rules.
rospd husky_bringup/udev > /dev/null
echo "Installing udev rules."
sudo cp *.rules /etc/udev/rules.d/
popd > /dev/null
udevadm trigger

# Install the upstart job, populate it with launch files.
install_pkg="rosrun robot_upstart install"
$install_pkg husky_base/launch --job husky-core
$install_pkg husky_teleop/launch --job husky-core --augment
$install_pkg husky_description/launch --job husky-core --augment

# Install the IMU launchers if it looks like an IMU is attached.
if [ -f /dev/clearpath/imu ]; then
  $install_pkg husky_bringup/launch/imu_config --job husky-core --augment
fi

# Install the NavSat launchers if it looks like a GPS is attached.
if [ -f /dev/clearpath/gps ]; then
  $install_pkg husky_bringup/launch/navsat_config --job husky-core --augment
fi

# TODO: Automatically detect more standard peripherals.
